Repository Swolify/swolify-fe, pull requests merged in 2022-07, with the labels that each got.

#16 Setup/deploy to gh pages
  package-lock.json
  package.json
  public/index.html
  src/index.js
Labels: FE

#18 Feature/side bar/ow
  cypress/e2e/profile-selection-spec.cy.js
  package-lock.json
  package.json
  public/index.html
  src/40DVWQ.jpeg
  src/856732.webp
  src/Components/Sidebar.js
  src/Styles/BingoView.css
  src/Styles/Sidebar.css
  src/Views/BingoView.js
Labels: enhancement, styling

#22 Feature/video component/ow
  src/App.js
  src/Components/Modal.js
  src/Components/Sidebar.js
  src/Components/Video.js
  src/Styles/Sidebar.css
  src/Views/BingoView.js
Labels: enhancement, setup, FE

#29 Feature/game play/ow
  src/Components/BingoSquare.js
  src/Components/Modal.js
  src/Components/Sidebar.js
  src/Styles/BingoView.css
  src/Views/BingoView.js
Labels: enhancement, FE

#40 Refactor/modal/ed
  src/Components/BingoCard.js
  src/Components/UserIcon.js
  src/Styles/BingoView.css
  src/Views/BingoView.js
Labels: FE

#41 Feature/game logic
  src/Components/Modal.js
  src/Components/Sidebar.js
  src/Views/BingoView.js
Labels: enhancement, FE

#46 Feature/flip cards/ow
  src/Components/Modal.js
  src/Components/Sidebar.js
  src/Styles/Sidebar.css
  src/Views/BingoView.js
Labels: bug, enhancement, FE

#51 Create Post
  src/App.js
  src/Components/GameSelectionForm.js
  src/Components/Modal.js
  src/Components/Sidebar.js
  src/Styles/Sidebar.css
  src/Views/BingoView.js
  src/index.js
Labels: MVP

#55 Create game history dynamically
  src/App.js
  src/Components/GameSelectionForm.js
  src/Components/GameStats.js
  src/Components/HistoryContainer.js
  src/Components/UserIcon.js
  src/Views/DashboardView.js
Labels: FE

#57 Feature/css profile/ow
  src/App.css
  src/Components/GameSelectionForm.js
  src/Components/HistoryContainer.js
  src/Components/LoadingScreen.js
  src/Components/Logo.js
  src/Components/Modal.js
  src/Components/PalmTree.js
  src/Components/Sidebar.js
  src/Components/SmallLogo.js
  src/Components/StartButton.js
  src/Components/UserIcon.js
  src/Components/Video.js
  src/Components/WinLossRatioChart.js
  src/Images/Large-logo.png
  src/Images/Swolify-logo.png
  src/Styles/BingoSquare.css
  src/Styles/BingoView.css
  src/Styles/DashboardView.css
  src/Styles/GameSelectionForm.css
  src/Styles/GameStats.css
  src/Styles/HistoryContainer.css
  src/Styles/LoadingScreen.css
  src/Styles/Logo.css
  src/Styles/Modal.css
  src/Styles/PalmTree.css
  src/Styles/ProfileView.css
  src/Styles/Sidebar.css
  src/Styles/StartButton.css
  src/Styles/UserIcon.css
  src/Styles/WinLossRatio.css
  src/Views/BingoView.js
  src/Views/DashboardView.js
  src/Views/ProfileView.js
  src/index.css
  src/sunset.webp
  src/synth-retrowave-synthwave-fon-new-retro-wave-sintveiv-ret-41.jpeg
Labels: enhancement, MVP, FE, styling

#59 Add return to homescreen and loss
  src/Components/HistoryContainer.js
  src/Components/Sidebar.js
  src/Styles/Sidebar.css
Labels: FE

#60 Create README and get rid of some code not being used
  README.md
  src/Components/UserIcon.js
  src/Components/WinLossRatioChart.js
Labels: documentation

#62 Feature/testing
  cypress/e2e/bingo-view-spec.cy.js
  cypress/e2e/dashboard-spec.cy.js
  cypress/e2e/profile-selection-spec.cy.js
  cypress/utils/graphql-test-utils.js
  src/Views/ProfileView.js
Labels: testing, MVP, FE
